[Global]
W = "1000"
H = "500"
duration = "1"
fps = "25"
format = "gif"
background = "black"

[Animations]

[RawSvgDefs.def1]
def = """
<linearGradient id="MyGradient">
    <stop offset="5%" stop-color="#F60"/>
    <stop offset="95%" stop-color="#FF6"/>
</linearGradient>
"""

[RawSvgDefs.def2]
def = """
<radialGradient id="MyGradient2" gradientUnits="userSpaceOnUse" cx="400" cy="200" r="300" fx="400" fy="200">\
    <stop offset="0%" stop-color="red"/>
    <stop offset="50%" stop-color="blue"/>
    <stop offset="100%" stop-color="red"/>
</radialGradient>
"""

[RawSvgDefs.def3]
def = """
<pattern id="star" viewBox="0,0,10,10" width="1%" height="10%" style="fill:yellow;">
  <polygon points="0,0 2,5 0,10 5,8 10,10 8,5 10,0 5,2" />
</pattern>
"""

[Styles.normal.StyleProperties]
text-anchor="middle"
fill="url(#MyGradient)"
stroke="black"
stroke-width="0.5px"
font-size="50"
font-family="sans-serif"

[Styles.normal2.StyleProperties]
text-anchor="middle"
fill="url(#MyGradient2)"
stroke="black"
stroke-width="0.5px"
font-size="30"
font-family="sans-serif"

[Styles.stars.StyleProperties]
text-anchor="middle"
fill="url(#star)"
stroke="yellow"
stroke-width="1px"
font-size="150"
font-family="sans-serif"

[RawSvgElementsUnder.element1]
element = """
<rect fill="url(#MyGradient2)" stroke="black" stroke-width="5" x="-500" y="-50" width="1000" height="100"/>
"""

[RawSvgElementsOver.element1]
element = """
<rect fill="url(#MyGradient)" stroke="black" stroke-width="5" x="-300" y="100" width="600" height="200"/>
"""


[Caption.Line1]
pos = "[0, 0]"
[Caption.Line1.Segments.Segment1]
text= "Simple caption on top of rectangle."
style = "${Styles.normal}"
[Caption.Line2]
pos = "[0, 100]"
[Caption.Line2.Segments.Segment1]
text = "A smaller caption overwritten by rectangle."
style = "${Styles.normal2}"
[Caption.Line3]
pos = "[0, -100]"
[Caption.Line3.Segments.Segment1]
text = "PATTERNS?!"
style = "${Styles.stars}"