[Global]
W = "1000"
H = "500"
duration = "1"
fps = "25"
format = "gif"
background = "black"

[Animations.Position.top_to_bottom]
type = "PointAnimation"
begin = "[0, -${Global.H}/3]"
end = "[0, ${Global.H}/3]"
tween = "linear"
ytween = "easeOutBounce"

[Styles.normal.StyleProperties]
text-anchor="middle"
fill="white"
stroke="black"
stroke-width="0.5px"
font-size="25"
font-family="sans-serif"

[Caption.Line1]
pos = "${Animations.Position.top_to_bottom}"
[Caption.Line1.PositionAnimation]
birth_time = "0"
begin_time = "${Global.duration}/4"
end_time = "${Global.duration}*2/3"
death_time = "${Global.duration}"
[Caption.Line1.Segments.Segment1]
text= "Simple caption that appears in the middle of the page."
style = "${Styles.normal}"