[Global]
W = "1000"
H = "500"
duration = "5"
fps = "25"
format = "gif"
background = "black"

[Animations.Filter.seedchange]
type = "NumberAnimation"
begin = "0"
end = "${Global.fps}*${Global.duration}/2.5"
tween = "linear"
[Animations.Filter.seedchange.FilterAnimation.seed]
birth_time = "0"
begin_time = "0"
end_time = "${Global.duration}"
death_time = "${Global.duration}"
[Animations.Filter.scalereduction]
type = "NumberAnimation"
begin = "25"
end = "0"
tween = "linear"
[Animations.Filter.scalereduction.FilterAnimation.scale]
birth_time = "0"
begin_time = "0"
end_time = "${Global.duration}"
death_time = "${Global.duration}"
[Animations.Filter.sharpen]
type = "NumberAnimation"
begin = "60"
end = "0"
tween = "easeOutQuad"
[Animations.Filter.sharpen.FilterAnimation.stdDeviationx]
birth_time = "0"
begin_time = "0"
end_time = "${Global.duration}*0.8"
death_time = "${Global.duration}"
[Animations.Filter.sharpen.FilterAnimation.stdDeviationy]
birth_time = "0"
begin_time = "0"
end_time = "${Global.duration}*0.5"
death_time = "${Global.duration}"
[Animations.Filter.dxred]
type="NumberAnimation"
begin="5"
end = "0"
tween="easeOutBounce"
[Animations.Filter.dxred.FilterAnimation.dx_red]
birth_time = "0"
begin_time = "1.3"
end_time = "${Global.duration}*0.5"
death_time = "${Global.duration}"
[Animations.Filter.dyred]
type="NumberAnimation"
begin="-6"
end = "0"
tween="easeOutBounce"
[Animations.Filter.dyred.FilterAnimation.dy_red]
birth_time = "0"
begin_time = "0.6"
end_time = "${Global.duration}*0.5"
death_time = "${Global.duration}"
[Animations.Filter.dxgreen]
type="NumberAnimation"
begin="4"
end = "0"
tween="easeOutBounce"
[Animations.Filter.dxgreen.FilterAnimation.dx_green]
birth_time = "0"
begin_time = "0.5"
end_time = "${Global.duration}*0.5"
death_time = "${Global.duration}"
[Animations.Filter.dygreen]
type="NumberAnimation"
begin="-3"
end = "0"
tween="easeOutBounce"
[Animations.Filter.dygreen.FilterAnimation.dy_green]
birth_time = "0"
begin_time = "0.6"
end_time = "${Global.duration}*0.5"
death_time = "${Global.duration}"
[Animations.Filter.dxblue]
type="NumberAnimation"
begin="7"
end = "0"
tween="easeOutBounce"
[Animations.Filter.dxblue.FilterAnimation.dx_blue]
birth_time = "0"
begin_time = "0.7"
end_time = "${Global.duration}*0.5"
death_time = "${Global.duration}"
[Animations.Filter.dyblue]
type="NumberAnimation"
begin="-5"
end = "0"
tween="easeOutBounce"
[Animations.Filter.dyblue.FilterAnimation.dy_blue]
birth_time = "0"
begin_time = "1"
end_time = "${Global.duration}*0.5"
death_time = "${Global.duration}"

[Styles.normal.StyleProperties]
text-anchor="middle"
fill="white"
stroke="black"
stroke-width="0.5px"
font-size="100"
font-family="sans-serif"
[Styles.small.StyleProperties]
text-anchor="middle"
fill="white"
stroke="black"
stroke-width="0.5px"
font-size="50"
font-family="sans-serif"

[Caption.Line1]
pos = "[0, 0]"
[Caption.Line1.Filter]
filter = "${Filters.displacement}" # points to displacement.svgtemplate in the templates/filter folder
[Caption.Line1.Filter.Overrides]
numOctaves = "1" # overrides default values specified in displacment.toml in the templates/filter folder
scale = "${Animations.Filter.scalereduction}"
seed = "${Animations.Filter.seedchange}"
[Caption.Line1.Segments.Segment1]
text= "Distortion"
style = "${Styles.normal}"
[Caption.Line2]
pos = "[0, 75]"
[Caption.Line2.Filter]
filter = "${Filters.blur}"
[Caption.Line2.Filter.Overrides]
stdDeviationx = "${Animations.Filter.sharpen}"
stdDeviationy = "${Animations.Filter.sharpen}"
[Caption.Line2.Segments.Segment1]
text = "Blur blur blur"
style = "${Styles.normal}"
[Caption.Line3]
pos = "[0, 175]"
[Caption.Line3.Filter]
filter = "${Filters.rgbsplit}"
[Caption.Line3.Filter.Overrides]
dx_red = "${Animations.Filter.dxred}"
dy_red = "${Animations.Filter.dyred}"
dx_green = "${Animations.Filter.dxgreen}"
dy_green = "${Animations.Filter.dygreen}"
dx_blue = "${Animations.Filter.dxblue}"
dy_blue = "${Animations.Filter.dyblue}"
[Caption.Line3.Segments.Segment1]
text = "RGB split?"
style= "${Styles.small}"
[Caption.Line4]
pos = "[0, -75]"
[Caption.Line4.Filter]
filter = "${Filters.dropshadow}"
[Caption.Line4.Filter.Overrides]
floodcolor = "#8f8b19"
[Caption.Line4.Segments.Segment1]
text = "drop it!"
style= "${Styles.small}"
[Caption.Line5]
pos = "[50, -175]"
[Caption.Line5.Filter]
filter = "${Filters.sketchy}"
[Caption.Line5.Filter.Overrides]
floodcolor = "#8f8b19"
[Caption.Line5.Segments.Segment1]
text = "sketchy?!"
style= "${Styles.normal}"
