[Global]
W = "1000"
H = "500"
duration = "10"
fps = "25"
format = "svg"
background = "black"

[Animations]
    [Animations.TextProvider.appear]
        type = "NumberAnimation"
        begin = "0"
        end = "100"
        tween = "easeOutQuad"
    [Animations.TextProvider.disappear]
        type = "NumberAnimation"
        begin = "100"
        end = "0"
        tween = "easeOutQuad"
    [Animations.TextProvider.reverse_appear]
        type = "NumberAnimation"
        begin = "0"
        end = "-100"
        tween = "easeOutQuad"
    [Animations.TextProvider.flash]
        type = "SequentialAnimation"
        elements = "[${Animations.TextProvider.appear}, ${Animations.TextProvider.disappear}]"
        time_weights = "[1,1]"
        repeats = "3"
        tween = "linear"
    [Animations.TextProvider.flash_and_appear]
        type = "SequentialAnimation"
        elements = "[${Animations.TextProvider.flash}, ${Animations.TextProvider.appear}]"
        time_weights = "[1,3]"
        repeats = "1"
        tween = "linear"
[Styles]
    [Styles.normal.StyleProperties]
        text-anchor="middle"
        fill="white"
        stroke="black"
        stroke-width="2px"
        font-size="55"
        font-family="sans-serif"
    [Styles.special.StyleProperties]
        text-anchor="middle"
        fill="blue"
        stroke="yellow"
        stroke-width="1px"
        font-size="70"
        font-family="sans-serif"
[Caption]
    [Caption.Line1]
        pos = "[0, 0]"
        [Caption.Line1.TextProvider]
            style = "${Animations.TextProvider.reverse_appear}"
        [Caption.Line1.TextProviderAnimation]
            birth_time = "0"
            begin_time = "0"
            end_time = "${Global.duration}/2"
            death_time = "${Global.duration}"
        [Caption.Line1.Segments]
            [Caption.Line1.Segments.Segment1]
                text= "Stuck in "
                style = "${Styles.normal}"
            [Caption.Line1.Segments.Segment2]
                style = "${Styles.special}"
                text = "the middle"
            [Caption.Line1.Segments.Segment3]
                style = "${Styles.normal}"
                text = " with you!"
